# Generated by Django 4.0.1 on 2022-01-08 22:00

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('descripcion', models.CharField(max_length=250)),
                ('liga', models.CharField(max_length=250)),
                ('fecha_creacion', models.DateTimeField(default=datetime.datetime.now)),
                ('creador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='equipo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rival',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('descripcion', models.CharField(blank=True, max_length=250, null=True)),
                ('fecha_creacion', models.DateTimeField(default=datetime.datetime.now)),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rivales', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('numero', models.IntegerField(null=True)),
                ('rol', models.CharField(choices=[('J', 'Jugador'), ('E', 'entrenador')], default='J', max_length=1)),
                ('fecha_creacion', models.DateTimeField(default=datetime.datetime.now)),
                ('equipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jugadores', to='api.equipo')),
                ('rival', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jugadores', to='api.rival')),
            ],
        ),
    ]
